module ApplicationHelper
  ################
  # 定数宣言

  # MeetingType IDs
  FREE_MEETING_TYPE_ID = 1
  PROJECT_MEETING_TYPE_ID = 2
  GROUP_MEETING_TYPE_ID = 3

  # ReceiverType IDs
  TO_TYPE_ID = 1
  CC_TYPE_ID = 2
  BCC_TYPE_ID = 3

  # グループ会議のメンバー範囲
  SELECT_GROUP_ID = 1
  PROGENY_GROUP_ID = 2
  RELATION_GROUP_ID = 3

  # プロジェクト会議のメンバー範囲
  SELECT_PROJECT_ID = 1
  PROGENY_PROJECT_ID = 2
  RELATION_PROJECT_ID = 3

  # 会議ステータスのID
  MEETING_STATUS_PLANNING_ID = 1
  MEETING_STATUS_EDITING_ID = 2
  MEETING_STATUS_INSPECTING_ID = 3
  MEETING_STATUS_APPROVING_ID = 4
  MEETING_STATUS_APPROVED_ID = 5
  MEETING_STATUS_PUBLISHED_ID = 6

end
